name: iChef Java Build and Test

on:
  push:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Setup MySql
        run: |
          sudo systemctl start mysql
          mysql -e 'CREATE DATABASE `${{ secrets.DB_DATABASE_NAME }}`;' -u${{ secrets.DB_USER }} -proot
          mysql -e "ALTER USER '${{ secrets.DB_USER }}'@'localhost' IDENTIFIED BY '${{ secrets.DB_PASSWORD }}'; FLUSH PRIVILEGES;" -u${{ secrets.DB_USER }} -proot

      - name: Build
        run: |
          cd iChef-WebApi
          mvn -B -DskipTests package --file pom.xml

      - name: Start Server
        run: |
          cd iChef-WebApi/target
          java -jar iChef-1.0.0.jar &

      - name: Test
        run: |
          cd iChef-WebApi
          mvn test
