name: iChef Java Build and Test

on:
  push:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Build
        run: |
          cd iChef-WebApi
          mvn -B -DskipTests package --file pom.xml

      - name: Test
        run: |
          cd iChef-WebApi
          mvn test
