name: iChef Java Build and Test

on:
  push:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'
  pull_request:
    branches: [ main ]
    paths: 
    - 'iChef-WebApi/**'
    - '.github/workflows/api-ci.yml'

env:
  DB_DATABASE: schema
  DB_USER: root
  DB_PASSWORD: 1234

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Test
        run: mysql -u root -h localhost -p '1234' -e 'show databases;'

      - name: Build
        run: |
          cd iChef-WebApi
          mvn -B -DskipTests package --file pom.xml
      
      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: '${{ env.DB_DATABASE }}' # Optional, default value is "test". The specified database which will be create
          mysql root password: ${{ env.DB_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password

      - name: Start Server
        run: |
          cd iChef-WebApi/target
          java -jar iChef-0.0.1-SNAPSHOT.jar

      - name: Test
        run: |
          cd iChef-WebApi
          mvn test
